export {
  POST_COMMUNITIES as COMMUNITIES,
  POST_CONTENT_RATINGS as CONTENT_RATINGS,
  canViewAdultPostContent as canViewAdult18Plus,
  canViewerSeePostClassification as canViewCommunity,
  getAllowedPostCommunityFilters as getAllowedCommunityFilters,
  getPostCommunityDefinition as getCommunityDefinition,
  getPostCommunityLabel as getCommunityLabel,
  getPostContentRatingLabel as getContentRatingLabel,
  getSafePostCommunity as normalizeCommunity,
  getSafePostContentRating as normalizeContentRating,
  isAdultPostClassification as isAdultCommunityOrRating,
  isPostCommunityType as isCommunityType,
  isPostContentRating as isContentRating,
  resolvePostContentRating as resolveContentRating,
  type PostClassificationViewer as CommunityViewer,
  type PostCommunityDefinition as CommunityDefinition,
  type PostCommunityFilter as CommunityFilter,
  type PostCommunityType as CommunityType,
  type PostContentRating as ContentRating,
} from '@/lib/post-classification'
